#apiVersion: v1
#kind: LimitRange
#metadata:
 # name: limits1
#spec:
 # limits:
  #  default:
   #   cpu: 500m
    #defaultRequest:
     # cpu: 500m
    #max:
     # cpu: "1"
    #min:
     # cpu: 100m
    #type: container

---
apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
    image: nginx:1.14.1
    name: limits
    imagePullPolicy: always
      resources:
        requests:
          memory: "64mi"
          cpu: "250m"
        limits:
          memory: "71mi"
          cpu: "300m"




---
