apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - image: nginx:1.14.2
      name: nginx
      ports:
        - containerPort: 80
    - image: almalinux:8
      name: sidecar
      command: ["sleep","200"]