apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - image: dmbabu/stress
      name: stress
      resources:
        requests:
          cup: "200m"
          memory: "150mi"
        limits:
          cpu: "500m"
          memory: "250mi"




