apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - image: dmbabu/stress
      name: resource
      imagePullPolicy: Always
      command: ["sleep","500"]
        resources:
          requests:
            memory: "64mi"
            cpu: "250m"
          limits:
            memory: "71mi"
            cpu: "300m"




